export const LOGIN='LOGIN';
export const LOGIN_FAILED='LOGIN_FAILED';

export const MANAGER_SIGNUP='MANAGER_SIGNUP';
export const MANAGER_SIGNUP_FAILED='MANAGER_SIGNUP_FAILED';

export const USER_SIGNUP='USER_SIGNUP';
export const USER_SIGNUP_FAILED='USER_SIGNUP_FAILED';

export const MANAGER_EDIT='MANAGER_EDIT';
export const MANAGER_EDIT_FAILED='MANAGER_EDIT_FAILED';

export const USER_EDIT = 'USER_EDIT';
export const USER_EDIT_FAILED = 'USER_EDIT_FAILED';

export const MANAGER_DELETE = 'MANAGER_DELETE';
export const USER_DELETE = 'USER_DELETE';

export const FETCH_MANAGER_REQUESTS = 'FETCH_MANAGER_REQUESTS';
export const FETCH_USER_REQUESTS = 'FETCH_USER_REQUESTS';
export const ADD_REQUEST = 'ADD_REQUEST';
export const DELETE_MANAGER_REQUEST = 'DELETE_MANAGER_REQUEST';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';

export const SHOW_ALERT = 'SHOW_ALERT';